# Custom Language File for Launcher Customizer

[ejs.app]
title = "TakumiLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Zubarashi7/TakumiLauncher"
mediaXURL = "https://x.com/TakumiLabs"
mediaInstagramURL = "https://www.instagram.com/takumilabs/"
mediaYouTubeURL = "https://www.youtube.com/channel/UCsTDent9oehbOlL5hWFd1bg"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/Zubarashi7/TakumiLauncher"
supportLink = "https://github.com/Zubarashi7/TakumiLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a TakumiLauncher"
welcomeDescription = "Nuestro launcher está diseñado para transformar la experiencia de los jugadores con juegos creados o inspirados en Minecraft, ofreciendo una plataforma intuitiva, eficiente y cargada de creatividad, que permite descubrir mundos personalizados, descargar actualizaciones con facilidad y disfrutar de un rendimiento optimizado, mientras conectas con una comunidad vibrante de jugadores apasionados por este universo único."
welcomeDescCTA = "¡Empieza tu aventura hoy!"
