[ejs.landing]
updateAvailableTooltip = "Actualización Disponible"
usernamePlaceholder = "Nombre de Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "FUERA DE LÍNEA"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No&nbsp;Esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; No Hay Servidor Seleccionado"
launchDetails = "Por favor espera.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Comprobando Noticias.."
newsErrorFailedSpan = "Error al Cargar las Noticias"
newsErrorRetryButton = "Intentar de Nuevo"
newsErrorNoneSpan = "Sin Noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "INICIO DE SESIÓN EN MINECRAFT"
loginEmailError = "* Valor no válido"
loginEmailPlaceholder = "CORREO ELECTRÓNICO O NOMBRE DE USUARIO"
loginPasswordError = "* Obligatorio"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "¿Olvidaste tu contraseña?"
loginRememberMeText = "¿Recordarme?"
loginButtonText = "INICIAR SESIÓN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¿Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envía directamente a Mojang y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no está afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de Inicio de Sesión"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
loginWithMojang = "Iniciar sesión con Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores Disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una Cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Listo"
tabAccountHeaderText = "Configuración de la Cuenta"
tabAccountHeaderDesc = "Añade nuevas cuentas o gestiona las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Añadir Cuenta de Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Añadir Cuenta de Mojang"
minecraftTabHeaderText = "Configuración de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del Juego"
launchFullscreenTitle = "Iniciar en pantalla completa."
autoConnectTitle = "Conectar automáticamente al servidor al iniciar."
launchDetachedTitle = "Lanzar el juego separado del launcher."
launchDetachedDesc = "Si el juego no está separado, cerrar el launcher también cerrará el juego."
tabModsHeaderText = "Configuración de Mods"
tabModsHeaderDesc = "Activa o desactiva mods."
switchServerButton = "Cambiar"
requiredMods = "Mods Requeridos"
optionalMods = "Mods Opcionales"
dropinMods = "Mods de Integración"
addMods = "Añadir Mods"
dropinRefreshNote = "(F5 para Actualizar)"
shaderpacks = "Paquetes de Shaders"
shaderpackDesc = "Activa o desactiva shaders. Ten en cuenta que los shaders solo funcionan bien en equipos potentes. Puedes añadir paquetes personalizados aquí."
selectShaderpack = "Seleccionar Paquete de Shaders"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Gestiona la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "La RAM mínima recomendada es de 3 gigabytes. Ajustar los valores mínimo y máximo al mismo puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar Ejecutable de Java"
javaExecSelButtonText = "Seleccionar Archivo"
javaExecDesc = "El ejecutable de Java se valida antes de lanzar el juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones Adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. <em>-Xms</em> y <em>-Xmx</em> no deben incluirse."
launcherTabHeaderText = "Configuración del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher."
allowPrereleaseTitle = "Permitir Actualizaciones en Pre-Lanzamiento."
allowPrereleaseDesc = "Los pre-lanzamientos incluyen nuevas funciones que pueden no haber sido completamente probadas o integradas.<br>Esto siempre será cierto si estás utilizando una versión en pre-lanzamiento."
dataDirectoryTitle = "Directorio de Datos"
selectDataDirectory = "Seleccionar Directorio de Datos"
chooseFolder = "Seleccionar Carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y los mundos guardados se almacenan en la carpeta de instancia de la configuración del servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión Estable"
versionText = "Versión "
sourceGithub = "Código Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de Herramientas de Desarrollador"
releaseNotes = "Notas de la Versión"
changelog = "Registro de Cambios"
noReleaseNotes = "No hay Notas de la Versión"
viewReleaseNotes = "Ver Notas de la Versión en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descarga, instala y revisa las actualizaciones del launcher."
checkForUpdates = "Buscar Actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Notas de la Actualización"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Esperando al Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de Sesión de Microsoft"
microsoftLogoutTitle = "Cierre de Sesión de Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Intentar de Nuevo"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Obligatorio"

[js.login.error.unknown]
title = "Error Desconocido Durante Inicio de Sesión"
desc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."

[js.landing.launch]
pleaseWait = "Por favor espera.."
failureTitle = "Error Durante el Lanzamiento"
failureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "No Se Ha Seleccionado Ninguna Cuenta"

[js.landing.selectedServer]
noSelection = "No Se Ha Seleccionado Ningún Servidor"
loading = "Cargando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "FUERA DE LÍNEA"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Comprobando información del sistema.."
noCompatibleJava = "No se Encontró una Instalación<br>Compatible de Java"
installJavaMessage = "Para iniciar Minecraft, necesitas una instalación de 64 bits de Java {major}. ¿Te gustaría que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando Descarga de Java.."
javaDownloadFailureTitle = "Error Durante la Descarga de Java"
javaDownloadFailureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
javaRequired = "Se Requiere Java<br>para Iniciar"
javaRequiredMessage = 'Se requiere una instalación válida de Java {major} x64 para iniciar.<br><br>Por favor, consulta nuestra <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guía de Gestión de Java</a> para instrucciones sobre cómo instalar Java manualmente.'
javaRequiredDismiss = "Entendido"
javaRequiredCancel = "Regresar"

[js.landing.downloadJava]
findJdkFailure = "No se encontró la distribución de OpenJDK."
javaDownloadCorruptedError = "El JDK descargado tiene un hash incorrecto, el archivo podría estar dañado."
extractingJava = "Extrayendo Java"
javaInstalled = "¡Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información del servidor.."
fatalError = "Error Fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del índice de distribución. Consulta la consola (CTRL + Shift + i) para más detalles."
pleaseWait = "Por favor espera.."
errorDuringLaunchTitle = "Error Durante el Lanzamiento"
seeConsoleForDetails = "Consulta la consola (CTRL + Shift + i) para más detalles."
validatingFileIntegrity = "Validando integridad de los archivos.."
errorDuringFileVerificationTitle = "Error Durante la Verificación de Archivos"
downloadingFiles = "Descargando archivos.."
errorDuringFileDownloadTitle = "Error Durante la Descarga de Archivos"
preparingToLaunch = "Preparándose para iniciar.."
launchingGame = "Iniciando el juego.."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargó correctamente. Como resultado, el juego no puede iniciar.<br><br>Para resolver este problema, desactiva temporalmente tu software antivirus e intenta iniciar el juego nuevamente.<br><br>Si tienes tiempo, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">reporta un problema</a> y dinos qué software antivirus utilizas. Nos pondremos en contacto con ellos e intentaremos solucionarlo."
doneEnjoyServer = "Hecho. ¡Disfruta del servidor!"
checkConsoleForDetails = "Por favor, consulta la consola (CTRL + Shift + i) para más detalles."

[js.landing.news]
checking = "Comprobando Noticias"

[js.landing.discord]
loading = "Cargando juego.."
joining = "Navegando hacia Westeros!"
joined = "Explorando el Reino!"

[js.overlay]
dismiss = "Cerrar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los Archivos"

[js.settings.mstfLogin]
errorTitle = "Algo Salió Mal"
errorMessage = "La autenticación de Microsoft falló. Por favor, inténtalo nuevamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Salió Mal"
errorMessage = "Error al cerrar sesión en Microsoft. Por favor, inténtalo de nuevo."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Seleccionar Cuenta"
selectedButton = "Cuenta Seleccionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es Tu Última Cuenta"
lastAccountWarningMessage = "Para usar el launcher debes tener al menos una cuenta iniciada. Necesitarás iniciar sesión nuevamente después.<br><br>¿Estás seguro de que quieres cerrar sesión?"
confirmButton = "Estoy Seguro"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nombre de Usuario"
uuid = "UUID"
selectAccount = "Seleccionar Cuenta"
selectedAccount = "Cuenta Seleccionada ✓"
logout = "Cerrar Sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Error al Eliminar<br>Mod de Integración {fullName}"
deleteFailedMessage = "Asegúrate de que el archivo no esté en uso e inténtalo de nuevo."
failedToggleTitle = "Error al Activar/Desactivar<br>Uno o Más Mods de Integración"
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección Inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones Disponibles para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-lanzamiento"
stableReleaseTitle = "Versión Estable"
releaseNotesFailed = "No se pudieron cargar las notas de la versión."

[js.settings.updates]
newReleaseTitle = "Nueva Versión Disponible"
newPreReleaseTitle = "Nuevo Pre-lanzamiento Disponible"
downloadingButton = "Descargando.."
downloadButton = 'Descargar desde GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cierra el launcher y ejecuta el dmg para actualizar.</span>'
latestVersionTitle = "Estás Usando la Versión Más Reciente"
checkForUpdatesButton = "Buscar Actualizaciones"
checkingForUpdatesButton = "Buscando Actualizaciones.."

[js.settings.msftLogin]
errorTitle = "Error en el Inicio de Sesión de Microsoft"
errorMessage = "No pudimos autenticar tu cuenta de Microsoft. Por favor, inténtalo de nuevo."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Error Fatal: No se Puede Cargar el Índice de Distribución"
fatalErrorMessage = "No se pudo establecer una conexión con nuestros servidores para descargar el índice de distribución. No se encontraron copias locales para cargar. <br><br>El índice de distribución es un archivo esencial que proporciona la información más reciente del servidor. El launcher no puede iniciarse sin él. Asegúrate de estar conectado a internet y relanza la aplicación."
closeButton = "Cerrar"

[js.uibinder.validateAccount]
failedMessageTitle = "Error al Actualizar el Inicio de Sesión"
failedMessage = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, selecciona otra cuenta o inicia sesión nuevamente."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, inicia sesión nuevamente."
loginButton = "Iniciar Sesión"
selectAnotherAccountButton = "Seleccionar Otra Cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando Actualizaciones..."
installNowButton = "Instalar Ahora"
checkForUpdatesButton = "Buscar Actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error Durante Inicio de Sesión:<br>Perfil No Configurado"
noProfileDesc = "Tu cuenta de Microsoft aún no tiene configurado un perfil de Minecraft. Si has comprado recientemente el juego o lo has canjeado a través de Xbox Game Pass, debes configurar tu perfil en <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si aún no has comprado el juego, también puedes hacerlo en <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error Durante Inicio de Sesión:<br>No Hay Cuenta de Xbox"
noXboxAccountDesc = "Tu cuenta de Microsoft no tiene una cuenta de Xbox asociada."
xblBannedTitle = "Error Durante Inicio de Sesión:<br>Xbox Live No Disponible"
xblBannedDesc = "Tu cuenta de Microsoft pertenece a un país donde Xbox Live no está disponible o está prohibido."
under18Title = "Error Durante Inicio de Sesión:<br>Aprobación Parental Requerida"
under18Desc = "Las cuentas para usuarios menores de 18 años deben ser añadidas a una Familia por un adulto."
unknownTitle = "Error Desconocido Durante Inicio de Sesión"
unknownDesc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."

[js.auth.mojang.error]
methodNotAllowedTitle = "Error Interno:<br>Método No Permitido"
methodNotAllowedDesc = "Método no permitido. Por favor, reporta este error."
notFoundTitle = "Error Interno:<br>No Encontrado"
notFoundDesc = "No se encontró el punto de autenticación. Por favor, reporta este problema."
accountMigratedTitle = "Error Durante Inicio de Sesión:<br>Cuenta Migrada"
accountMigratedDesc = "Has intentado iniciar sesión con una cuenta migrada. Intenta nuevamente usando el correo electrónico de la cuenta como nombre de usuario."
invalidCredentialsTitle = "Error Durante Inicio de Sesión:<br>Credenciales Inválidas"
invalidCredentialsDesc = "El correo electrónico o la contraseña que has ingresado son incorrectos. Por favor, inténtalo de nuevo."
tooManyAttemptsTitle = "Error Durante Inicio de Sesión:<br>Demasiados Intentos"
tooManyAttemptsDesc = "Ha habido demasiados intentos de inicio de sesión recientes con esta cuenta. Por favor, inténtalo más tarde."
invalidTokenTitle = "Error Durante Inicio de Sesión:<br>Token Inválido"
invalidTokenDesc = "El token de acceso proporcionado no es válido."
tokenHasProfileTitle = "Error Durante Inicio de Sesión:<br>Token Tiene Perfil"
tokenHasProfileDesc = "El token de acceso ya tiene un perfil asignado. La selección de perfiles aún no está implementada."
credentialsMissingTitle = "Error Durante Inicio de Sesión:<br>Faltan Credenciales"
credentialsMissingDesc = "No se han proporcionado el nombre de usuario/contraseña o la contraseña tiene menos de 3 caracteres."
invalidSaltVersionTitle = "Error Durante Inicio de Sesión:<br>Versión de Salt Inválida"
invalidSaltVersionDesc = "Versión de salt inválida."
unsupportedMediaTypeTitle = "Error Interno:<br>Tipo de Medio No Soportado"
unsupportedMediaTypeDesc = "Tipo de medio no soportado. Por favor, reporta este error."
accountGoneTitle = "Error Durante Inicio de Sesión:<br>Cuenta Migrada"
accountGoneDesc = "La cuenta ha sido migrada a una cuenta de Microsoft. Por favor, inicia sesión con Microsoft."
unreachableTitle = "Error Durante Inicio de Sesión:<br>Inalcanzable"
unreachableDesc = "No se puede acceder a los servidores de autenticación. Asegúrate de que estén en línea y de que estés conectado a internet."
gameNotPurchasedTitle = "Error Durante Inicio de Sesión:<br>Juego No Comprado"
gameNotPurchasedDesc = "La cuenta con la que intentas iniciar sesión no ha comprado una copia de Minecraft. Puedes adquirir una copia en <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Error Desconocido Durante Inicio de Sesión"
unknownErrorDesc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."
